name: pelican
channels:
- defaults
dependencies:
- pip
- jinja2
- click
- psutil
# OWSLib
- lxml
# opendap support
- netcdf4
# dask
- xarray
# plot
- cartopy
- matplotlib
# tests
- pytest
- pip:
  - -e git+https://github.com/geopython/pywps@master#egg=pywps
  - -e git+https://github.com/bird-house/OWSLib-esgfwps.git@master#egg=owslib-esgfwps
