name: pelican
channels:
- conda-forge
- birdhouse
dependencies:
- pywps=4.2
- jinja2
- click
- psutil
# owslib esgfwps
- owslib>=0.17
- owslib-esgfwps=0.1.0
# opendap support
- netcdf4
# dask
- xarray
# plot
- cartopy
- matplotlib
#- pip:
#  - -e git+https://github.com/bird-house/OWSLib-esgfwps.git@master#egg=owslib-esgfwps
